### ISSUE TITLE
Problem with alias-resolve-loader

### ISSUE THREAD

**Issue by domsayswow** [yibn2008/fast-sass-loader#2]
I am using alias-resolve-loader to pull a directory that exists outside of package.json directory tree, and then importing that file into style.scss. This works fine with sass-loader, but fails using fast-sass. 

```
aliasesResolve: {
    "@siteStyle" : SITES_PATH + process.env.TSJ_SITE + '/static/scss'
},

@import "@siteStyle/style.scss";

'ERROR in ./~/css-loader!./~/fast-sass-loader!./~/alias-resolve-loader!./bootstrap4/static/tsj_core/scss/style.scss
Module build failed: Error: import file cannot be resolved: "@import "../../../tsj-mt/sites/bs4transition/static/scss/style.scss";" @/home/vagrant/.virtualenvs/tsj-mt/src/tsj-ui/tsj_ui/bootstrap4/static/tsj_core/scss/style.scss
    at Object.importReplacer (/home/vagrant/.virtualenvs/tsj-mt/src/tsj-ui/tsj_ui/node_modules/fast-sass-loader/index.js:131:19)
    at throw (native)
    at onRejected (/home/vagrant/.virtualenvs/tsj-mt/src/tsj-ui/tsj_ui/node_modules/co/index.js:81:24)
 @ ./bootstrap4/static/tsj_core/scss/style.scss 4:14-196 13:2-17:4 14:20-202'
```

Any help would be greatly appreciated!

**Comment by yibn2008** [comment]
please provide your full webpack.config.js
