### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by pavelloz** [yibn2008/fast-sass-loader#28]
I just tried to experiment with the simplest setup -- i assume this error is the same as in many other plugins on webpack 4 :)

```ERROR in ./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/app.scss
Module build failed: TypeError: Cannot read property 'context' of undefined
    at getLoaderConfig (/Users/pavel/projects/xx/node_modules/fast-sass-loader/lib/index.js:72:29)
    at Object.module.exports (/Users/pavel/projects/xx/node_modules/fast-sass-loader/lib/index.js:224:17)
 @ ./src/app.scss 4:14-127
 @ ./src/app.js
```

**Comment by Natumsol** [comment]
The error still exist in Version 1.4.0，hope fix it soon :-)

**Comment by yibn2008** [comment]
@Natumsol 1.4.1 has been released, try it.

**Comment by Natumsol** [comment]
Wow, very nice😀
