### ISSUE TITLE
Webpack 4 error

### ISSUE THREAD

**Issue by frenic** [yibn2008/fast-sass-loader#31]
I get this error using fast-sass-loader@1.4 with Webpack@4.1.1.

```
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'context' of undefined
      at getLoaderConfig (C:\path\to\node_modules\fast-sass-loader\lib\index.js:72:29)
      at Object.module.exports (C:\path\to\node_modules\fast-sass-loader\lib\index.js:224:17)
      at runLoaders (C:\path\to\node_modules\webpack\lib\NormalModule.js:236:20)
      at C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:364:11
      at C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:230:18
      at runSyncOrAsync (C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
      at iterateNormalLoaders (C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
      at iterateNormalLoaders (C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
      at C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:233:3
      at runSyncOrAsync (C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
      at iterateNormalLoaders (C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
      at Array.<anonymous> (C:\path\to\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
```

**Comment by yibn2008** [comment]
@frenic try to use `fast-sass-loader@1.4.1`
