### ISSUE TITLE
Problem in jest tests fast-sass-loader/lib/index.js is not a loader

### ISSUE THREAD

**Issue by DavidBabel** [yibn2008/fast-sass-loader#38]
i got this full error : 

```
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:195
    Error: Module '/formats/node_modules/fast-sass-loader/lib/index.js' is not a loader (must have normal or pitch function)
        at loadLoader (/formats/node_modules/loader-runner/lib/loadLoader.js:35:10)
        at iteratePitchingLoaders (/formats/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/formats/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /formats/node_modules/loader-runner/lib/LoaderRunner.js:173:18
        at loadLoader (/formats/node_modules/loader-runner/lib/loadLoader.js:36:3)
        at iteratePitchingLoaders (/formats/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/formats/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
        at NormalModule.doBuild (/formats/node_modules/webpack/lib/NormalModule.js:179:3)
        at NormalModule.build (/formats/node_modules/webpack/lib/NormalModule.js:268:15)
        at Compilation.buildModule (/formats/node_modules/webpack/lib/Compilation.js:146:10)
        at factoryCallback (/formats/node_modules/webpack/lib/Compilation.js:329:11)
        at factory (/formats/node_modules/webpack/lib/NormalModuleFactory.js:253:5)
        at applyPluginsAsyncWaterfall (/formats/node_modules/webpack/lib/NormalModuleFactory.js:99:14)
        at /formats/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
        at NormalModuleFactory.params.normalModuleFactory.plugin (/formats/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (/formats/node_modules/webpack/node_modules/tapable/lib/Tapable.js:272:13)
        at resolver (/formats/node_modules/webpack/lib/NormalModuleFactory.js:74:11)
        at process.nextTick (/formats/node_modules/webpack/lib/NormalModuleFactory.js:205:8)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by yibn2008** [comment]
please provide webpack config and version which can reproduce this, an example repo will also be great.
