### ISSUE TITLE
Its crashing with the latest version of vue-loader: Cannot read property 'getTime' of undefined

### ISSUE THREAD

**Issue by milewski** [yibn2008/fast-sass-loader#42]
```
Failed to compile.

Module build failed (from ../node_modules/fast-sass-loader/lib/index.js):
TypeError: Cannot read property 'getTime' of undefined
    at Cache.write (/Users/milewski/Code/frontend/node_modules/fast-sass-loader/lib/cache.js:109:48)
    at /Users/milewski/Code/frontend/node_modules/fast-sass-loader/lib/index.js:290:15
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/milewski/Code/frontend/node_modules/co/index.js:65:19)
```

```
"webpack": "^4.17.1",
"vue-loader": "15.4.0",
```

**Comment by milewski** [comment]
Actually i have narrowed the problem down to `vue-loader: 15.4.0` (https://github.com/vuejs/vue-loader/pull/1384), using `vue-loader: 15.3.0` works perfectly

**Comment by yibn2008** [comment]
+ fast-sass-loader@1.4.6

@milewski try this version

**Comment by milewski** [comment]
@yibn2008 worked. thanks! 👍
