### ISSUE TITLE
unsupported previous source map format: true when I use with post-css loader

### ISSUE THREAD

**Issue by scottdickerson** [yibn2008/fast-sass-loader#65]
```
ERROR in ./src/sass/main.scss (./node_modules/css-loader??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/fast-sass-loader/lib??ref--7-3!./src/sass/main.scss)
    Module build failed (from ./node_modules/postcss-loader/src/index.js):
    Error: Unsupported previous source map format: true
  at PreviousMap.loadMap (/Users/scottsd/Documents/GitHub/common-core-external-dashboard/node_modules/postcss-loader/node_modules/postcss/lib/previous-map.js:133:15)
        at new PreviousMap (/Users/scottsd/Documents/GitHub/common-core-external-dashboard/node_modules/postcss-loader/node_modules/postcss/lib/previous-map.js:51:21)
        at new Input (/Users/scottsd/Documents/GitHub/common-core-external-dashboard/node_modules/postcss-loader/node_modules/postcss/lib/input.js:80:15)
       
```

webpack config
```
   {
                loader: 'postcss-loader',
                options: { sourceMap: true },
              },
              {
                loader: 'fast-sass-loader'
              }

```

webpack versions 4.42.1, fast-sass-loader: 1.5.0, postcss-loader: 3.0.0

**Comment by scottdickerson** [comment]
this is bogus, was due to a package.json issue
